import { Injectable } from '@angular/core';
import { delay, Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class SearchService {
  private readonly games = [
    'A Plague Tale: Innocence',
    'A Way Out',
    'AI: The Somnium Files',
    "Alan Wake's American Nightmare",
    'Alice: Madness Returns',
    'Alien: Isolation',
    'Aliens: Fireteam Elite',
    'Among Us',
    'Anthem',
    'ANVIL: Vault Breaker',
    'Aragami 2',
    'Archvale',
    'ARK: Survival Evolved',
    'Army of TWO',
    'art of rally',
    'Astria Ascending',
    'Astroneer',
    'Atomicrops',
    'Back 4 Blood',
    'Backbone',
    'Banjo-Kazooie',
    'Banjo-Kazooie: Nuts & Bolts',
    'Banjo-Tooie',
    'Bassmaster Fishing 2022',
    'Batman: Arkham Knight',
    'Battlefield 1',
    'Battlefield 1943',
    'Battlefield 3',
    'Battlefield 4',
    'Battlefield Hardline',
    'Battlefield V',
    'Battlefield: Bad Company',
    'Battlefield: Bad Company 2',
    'Battletoads',
    'Before We Leave',
    'Bejeweled 2',
    'Bejeweled 3',
    'Ben 10: Power Trip',
    'Besiege Console',
    'Black Desert',
    'Bleeding Edge',
    'Bloodroots',
    'Boyfriend Dungeon',
    'Breathedge',
    'Bridge Constructor Portal',
    'Broken Age',
    'Brütal Legend',
    'Bug Fables: The Everlasting Sapling',
    'Burnout Paradise Remastered',
    'Carrion',
    'Children of Morta',
    'Cities: Skylines',
    'ClusterTruck',
    'Conan Exiles',
    'Contrast',
    'Costume Quest 2',
    'Crackdown 3: Campaign',
    'Crackdown 3: Wrecking Zone',
    'Craftopia',
    'Cricket 19',
    'Cris Tales',
    'Crown Trick',
    'Crysis',
    'Crysis 2',
    'Crysis 3',
    'Curse of the Dead Gods',
    'Dandy Ace',
    'Danganronpa: Trigger Happy Havoc Anniversary Edition',
    "Dante's Inferno",
    'Dark Alliance',
    'Darkest Dungeon',
    'Day of the Tentacle Remastered',
    'DayZ',
    'Dead by Daylight',
    'Dead Cells',
    'Dead Space (Xbox 360)',
    'Dead Space 2',
    'Dead Space 3',
    'Dead Space: Ignition',
    "Death's Door",
    'DEEEER Simulator: Your Average Everyday Deer Game',
    'Deep Rock Galactic',
    'Descenders',
    'Destroy All Humans!',
    'Dicey Dungeons',
    'DiRT 4',
    'DIRT 5',
    'DiRT Rally',
    'DiRT Rally 2.0',
    'Dishonored 2',
    'Dishonored Definitive Edition',
    'Dishonored: Death of the Outsider',
    'Disneyland Adventures',
    'Dodgeball Academia',
    'Donut County',
    'DOOM',
    'DOOM (1993)',
    'DOOM 3',
    'DOOM 64',
    'DOOM Eternal',
    'DOOM II (Classic)',
    'Double Dragon Neon',
    'Dragon Age II',
    'Dragon Age: Inquisition',
    'Dragon Age: Origins',
    'Dragon Ball FighterZ',
    'Dragon Quest Builders 2',
    'DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition',
    'DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition (JP)',
    'Dreamscaper',
    'EA SPORTS Rory McIlroy PGA TOUR',
    'EA SPORTS UFC 3',
    'EA SPORTS UFC 4',
    'Echo Generation',
    'Edge of Eternity',
    'Elite: Dangerous',
    'Embr',
    'Empire of Sin',
    'Enter the Gungeon',
    'Evil Genius 2: World Domination',
    'Exo One',
    'F1 2019',
    'F1 2020',
    'Fable Anniversary',
    'Fable II',
    'Fable III',
    'Fae Tactics',
    'Fallout 3',
    'Fallout 4',
    'Fallout 76',
    'Fallout: New Vegas',
    'FAR: Changing Tides',
    'Farming Simulator 19',
    'Fe',
    'Feeding Frenzy',
    'Feeding Frenzy 2: Shipwreck Showdown',
    'FIFA 20',
    'FIFA 21',
    'FIFA 21 (Xbox One)',
    'Fight Night Champion',
    'Final Fantasy X/X-2 HD Remaster',
    'Final Fantasy XIII',
    'Final Fantasy XIII-2',
    'Firewatch',
    'Flynn: Son of Crimson',
    'Football Manager 2022 Xbox Edition',
    'For Honor',
    'Forager',
    'Forza Horizon 4',
    'Forza Horizon 5',
    'Frostpunk: Console Edition',
    'Full Throttle Remastered',
    'Gang Beasts',
    'Gears 5',
    'Gears of War',
    'Gears of War 2',
    'Gears of War 3',
    'Gears of War 4',
    'Gears of War: Judgment',
    'Gears of War: Ultimate Edition',
    'Gears Tactics',
    'Generation Zero',
    'Genesis Noir',
    'Goat Simulator',
    'Going Under',
    'Golf With Your Friends',
    'Gorogoa',
    'Grand Theft Auto: San Andreas – The Definitive Edition',
    'GreedFall',
    'GRID',
    'Grim Fandango Remastered',
    'Grounded',
    'Hades',
    'Halo 5: Guardians',
    'Halo Infinite',
    'Halo Wars 2',
    'Halo Wars: Definitive Edition',
    'Halo: Spartan Assault',
    'Halo: The Master Chief Collection',
    'Heavy Weapon',
    "Hellblade: Senua's Sacrifice",
    'HITMAN',
    'HITMAN 2',
    'HITMAN 3',
    'Hollow Knight: Voidheart Edition',
    'Human Fall Flat',
    'I Am Fish',
    'Immortal Realms: Vampire Wars',
    'Infernax',
    'Injustice 2',
    'Into the Pit',
    'It Takes Two',
    'Jetpac Refuelled',
    'Joy Ride Turbo',
    'Jurassic World Evolution',
    'Just Cause 4',
    'Kameo: Elements of Power',
    'Katamari Damacy Reroll',
    'Kentucky Route Zero: TV Edition',
    'Kill It With Fire',
    'Killer Instinct',
    'Killer Instinct 2 Classic',
    'Killer Instinct Classic',
    'Knockout City',
    'Lake',
    'Last Stop',
    'Lawn Mowing Simulator',
    'Lemnis Gate',
    'Lethal League Blaze',
    'Library Of Ruina',
    'Lightning Returns: Final Fantasy XIII',
    'LIMBO',
    'Lonely Mountains: Downhill',
    'Lost Words: Beyond the Page',
    'Lumines Remastered',
    'Madden NFL 20',
    'Madden NFL 21',
    'Madden NFL 21 (Xbox One)',
    'Madden NFL 22',
    'Madden NFL 22 (Xbox One)',
    'Maneater',
    "Marvel's Avengers",
    "Marvel's Guardians of the Galaxy",
    'Mass Effect',
    'Mass Effect 2',
    'Mass Effect 3',
    'Mass Effect Legendary Edition',
    'Mass Effect: Andromeda',
    'Max: The Curse of Brotherhood',
    'MechWarrior 5: Mercenaries',
    'Medal of Honor: Airborne',
    'Microsoft Flight Simulator',
    'Middle-earth: Shadow of War',
    'Mighty Goose',
    'Mind Scanners',
    'Minecraft',
    'Minecraft Dungeons',
    "Mirror's Edge",
    "Mirror's Edge Catalyst",
    'MLB The Show 21',
    'Monster Sanctuary',
    'Monster Train',
    'Moonglow Bay',
    'Moonlighter',
    'Mortal Kombat 11',
    'Mortal Shell: Enhanced Edition',
    'MotoGP 20',
    'My Friend Pedro',
    'My Time at Portia',
    'Myst',
    'Narita Boy',
    'NBA LIVE 19',
    'Need for Speed',
    'Need for Speed Heat',
    'Need for Speed Hot Pursuit Remastered',
    'Need for Speed Payback',
    'Need for Speed Rivals',
    'Neon Abyss',
    'Neoverse',
    "New Super Lucky's Tale",
    'Next Space Rebels',
    'NHL 20',
    'NHL 21',
    'NHL 94 Rewind',
    'NieR: Automata BECOME AS GODS Edition',
    "No Man's Sky",
    'Nobody Saves the World',
    'Nongunz: Doppelganger Edition',
    'Nuclear Throne',
    'Octopath Traveler',
    'Olija',
    'Omno',
    'ONE PIECE: PIRATE WARRIORS 4',
    'One Step From Eden',
    'Ori and the Blind Forest: Definitive Edition',
    'Ori and the Will of the Wisps',
    'Outer Wilds',
    'Outlast 2',
    'Outriders',
    'Overcooked! 2',
    'PAW Patrol: Mighty Pups Save Adventure Bay',
    'Payday 2: Crimewave Edition',
    'Peggle',
    'Peggle 2',
    'Perfect Dark (Xbox 360)',
    'Perfect Dark Zero',
    'Phoenix Point',
    'PHOGS!',
    'Pikuniku',
    'Pillars of Eternity',
    'Pillars Of Eternity II: Deadfire',
    'Plants vs. Zombies',
    'Plants vs. Zombies Garden Warfare',
    'Plants vs. Zombies Garden Warfare 2',
    'Plants vs. Zombies: Battle for Neighborville',
    'Power Rangers: Battle for the Grid',
    'Prey',
    'Project Wingman',
    'Psychonauts 2',
    'Pupperazzi',
    'Quake',
    'Quantum Break',
    'Race with Ryan',
    'RAGE',
    'RAGE 2',
    'Rain on Your Parade',
    'Raji: An Ancient Epic',
    'Rare Replay',
    'Recompile',
    'Record of Lodoss War -Deedlit in Wonder Labyrinth-',
    'ReCore',
    'Remnant: From the Ashes',
    'Resident Evil 7: Biohazard',
    'Resident Evil 7: Biohazard Grotesque Ver.',
    'Ring of Pain',
    'Rocket Arena',
    'Rubber Bandits',
    'Rush: A Disney Pixar Adventure',
    'Ryse: Son of Rome',
    'Sable',
    'Scarlet Nexus',
    'ScreamRide',
    'Sea of Solitude',
    'Sea of Thieves',
    'Second Extinction',
    'Secret Neighbor',
    'Serious Sam 4',
    'Shadow Warrior 2',
    'Signs of the Sojourner',
    'Skate 3',
    'skate.',
    'SkateBIRD',
    'Skul: The Hero Slayer',
    'Slay The Spire',
    'Slime Rancher',
    'Sniper Elite 4',
    'SnowRunner',
    'Space Warlord Organ Trading Simulator',
    'Spelunky 2',
    'Spiritfarer: Farewell Edition',
    'SSX',
    'Star Wars Battlefront',
    'Star Wars Battlefront II',
    'Star Wars Jedi: Fallen Order',
    'Star Wars: Squadrons',
    'Stardew Valley',
    'State of Decay 2: Juggernaut Edition',
    'State of Decay: Year-One',
    'Steep',
    'Stellaris: Console Edition',
    'Streets of Rage 4',
    'Subnautica',
    'Subnautica: Below Zero',
    'Sunset Overdrive',
    "Super Lucky's Tale",
    'Super Mega Baseball 3',
    'SUPERHOT: MIND CONTROL DELETE',
    'Superliminal',
    'Supraland',
    'Surgeon Simulator 2',
    'Taiko no Tatsujin: The Drum Master!',
    'Tell Me Why',
    'Telling Lies',
    'Terraria',
    'Tetris Effect: Connected',
    'The Artful Escape',
    'The Ascent',
    "The Bard's Tale ARPG : Remastered and Resnarkled",
    "The Bard's Tale IV: Director's Cut",
    "The Bard's Tale Trilogy",
    'The Catch: Carp & Coarse Fishing',
    'The Elder Scrolls IV: Oblivion',
    'The Elder Scrolls Online',
    'The Elder Scrolls V: Skyrim Special Edition',
    'The Evil Within',
    'The Evil Within (JP)',
    'The Evil Within 2',
    'The Forgotten City',
    'The Good Life',
    'The Gunk',
    'The Last Kids on Earth and the Staff of Doom',
    'The Long Dark',
    'The Outer Worlds',
    'The Pedestrian',
    'The Procession to Calvary',
    'The Riftbreaker',
    'The Sims 4',
    'The Surge 2',
    'The Walking Dead',
    'The Walking Dead: A New Frontier',
    'The Walking Dead: Michonne',
    'The Walking Dead: Season Two',
    'The Wild at Heart',
    'theHunter: Call of the Wild',
    'Titanfall 2',
    "Tom Clancy's Rainbow Six Extraction",
    "Tom Clancy's Rainbow Six Siege",
    'Torchlight III',
    'Totally Accurate Battle Simulator',
    'Totally Reliable Delivery Service',
    'Townscaper',
    'Trailmakers',
    'Train Sim World 2',
    'Transformers: Battlegrounds',
    'Tropico 6',
    'Twelve Minutes',
    'Two Point Hospital',
    'Undertale',
    'Undungeon',
    'Unpacking',
    'Unravel',
    'Unravel Two',
    'UNSIGHTED',
    'Visage',
    'Viva Piñata',
    'Viva Piñata: Trouble In Paradise',
    'Warhammer 40,000: Battlesector',
    "Wasteland 2: Director's Cut",
    'Wasteland 3',
    'Wasteland Remastered',
    'We Happy Few',
    'Weird West',
    'What Remains of Edith Finch',
    'Windjammers 2',
    'Wolfenstein II: The New Colossus',
    'Wolfenstein: The New Order',
    'Wolfenstein: The Old Blood',
    'Wolfenstein: Youngblood',
    'World War Z',
    'Worms Rumble',
    'Worms W.M.D.',
    'Wreckfest',
    'Yakuza 3 Remastered',
    'Yakuza 4 Remastered',
    'Yakuza 5 Remastered',
    'Yakuza 6: The Song of Life',
    'Yakuza: Like a Dragon',
    'Yes, Your Grace',
    'Young Souls',
    'Zombie Army 4: Dead War',
    'Zoo Tycoon: Ultimate Animal Collection',
    'Zuma',
    "Zuma's Revenge!",
  ];

  constructor() {}

  public search(query?: string): Observable<string[]> {
    console.log(`${new Date()} Search: ${query}`);

    if (query === undefined || query.length === 0) {
      return of([]);
    }

    const result = this.games.filter((game) =>
      game.toLowerCase().includes(query.toLowerCase())
    );

    return of(result).pipe(delay(1000));
  }
}
